import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModeToggle } from "../components/mode-toggle";
const inter = Inter({ subsets: ["latin"] });
import Provider from "./provider";
import Header from "./header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {" "}
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
